const portal=document.getElementById('portal'),content=document.getElementById('portal-content');
const openPortal=(type)=>{portal.classList.remove('hidden');content.innerHTML=type==='faculty'?faculty():student();};
const student=()=>`<p class="eyebrow">STUDENT LOGIN</p><h2>Student Login</h2><p>Enter your college roll number and password to access quizzes, results and rankings.</p><input id="studentRoll" placeholder="Roll Number"><input id="studentPassword" type="password" placeholder="Password"><button class="primary" id="studentLogin">Login to Student Portal →</button><p id="loginMsg" class="message"></p><div class="portal-links"><button type="button">📷 Scan Quiz QR</button><button type="button">🔗 Join by Quiz Link</button></div>`;
const faculty=()=>`<p class="eyebrow">FACULTY LOGIN</p><h2>Faculty Login</h2><p>Sign in using your faculty name and password to create quizzes and view reports.</p><input id="facultyName" placeholder="Faculty Name"><input id="facultyPassword" type="password" placeholder="Password"><button class="primary" id="facultyLogin">Login to Faculty Dashboard →</button><p id="loginMsg" class="message"></p><div class="portal-links"><button type="button">➕ Create Quiz</button><button type="button">📊 View Reports</button></div>`;
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>openPortal(b.dataset.view)));
document.querySelector('.close').addEventListener('click',()=>portal.classList.add('hidden'));
portal.addEventListener('click',e=>{if(e.target===portal)portal.classList.add('hidden')});
document.addEventListener('click',e=>{
 if(e.target.id==='studentLogin'){const roll=document.getElementById('studentRoll').value.trim(),pass=document.getElementById('studentPassword').value.trim(),m=document.getElementById('loginMsg');if(!roll||!pass){m.textContent='Please enter your roll number and password.';return}m.textContent='Student login details accepted. Secure authentication will be connected to the database next.'}
 if(e.target.id==='facultyLogin'){const name=document.getElementById('facultyName').value.trim(),pass=document.getElementById('facultyPassword').value.trim(),m=document.getElementById('loginMsg');if(!name||!pass){m.textContent='Please enter your faculty name and password.';return}m.textContent='Faculty login details accepted for '+name+'. Secure authentication will be connected to the database next.'}
});
document.querySelector('.menu').addEventListener('click',()=>document.querySelector('nav').classList.toggle('mobile-open'));